# Generated by Django 5.1.7 on 2025-10-14 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='repost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='hashtags', to='posts.post'),
        ),
        migrations.AlterUniqueTogether(
            name='repost',
            unique_together={('original_post', 'user')},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='posts_comme_post_id_94ac6b_idx'),
        ),
        migrations.AddIndex(
            model_name='hashtag',
            index=models.Index(fields=['name'], name='posts_hasht_name_1acbc9_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['post', 'user'], name='posts_like_post_id_d262ec_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='posts_post_created_183a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created_at'], name='posts_post_author__f8ea20_idx'),
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(fields=['post', 'user'], name='posts_postv_post_id_fdfc95_idx'),
        ),
    ]
