# Generated by Django 5.1.7 on 2025-08-04 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('TUTOR', 'Tutor'), ('ADMIN', 'Admin')], default='STUDENT', help_text='Role of the user on the platform.', max_length=10)),
                ('is_approved_tutor', models.BooleanField(default=False, help_text='Designates if a tutor account has been approved by an admin.')),
                ('avatar', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, help_text='A short biography about the user.', null=True)),
                ('github', models.URLField(blank=True, help_text='Link to GitHub profile', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='Link to LinkedIn profile', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
