# Generated by Django 5.1.7 on 2025-10-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived'), ('PRIVATE', 'Private')], default='DRAFT', help_text='Current status of the article (e.g., Draft, Pending Approval, Published).', max_length=20),
        ),
    ]
