# render.yaml
# This file defines the services for your Django project on Render.

services:
  # ----------------- #
  #  PostgreSQL DB    #
  # ----------------- #
  - type: psql
    name: MockMateDB
    plan: free 

  # ----------------- #
  #  Django Web App   #
  # ----------------- #
  - type: web
    name: mockmate-web
    plan: free
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mockmate01.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: psql
          name: MockMateDB
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.11.4
      # IMPORTANT: Add your actual secret keys in the Render dashboard
      - key: JDOODLE_CLIENT_ID
        value: "YOUR_JDOODLE_CLIENT_ID_HERE"
      - key: JDOODLE_CLIENT_SECRET
        value: "YOUR_JDOODLE_CLIENT_SECRET_HERE"
      - key: GEMINI_API_KEY
        value: "YOUR_GEMINI_API_KEY_HERE"

