# Generated by Django 5.1.7 on 2025-08-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceproblem',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='PUBLISHED', help_text='Current status of the problem (e.g., Draft, Pending Approval, Published).', max_length=20),
        ),
    ]
