# Generated by Django 5.1.7 on 2025-08-04 14:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockInterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(help_text='Target job role for the interview.', max_length=255)),
                ('key_skills', models.TextField(blank=True, help_text='Comma-separated key skills provided by the user.')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('COMPLETED', 'Completed'), ('REVIEW_PENDING', 'Review Pending'), ('REVIEWED', 'Reviewed'), ('CANCELLED', 'Cancelled')], default='STARTED', help_text='Current status of the mock interview session.', max_length=20)),
                ('overall_feedback', models.TextField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Overall score for the interview (e.g., 0-100).', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mock Interview Session',
                'verbose_name_plural': 'Mock Interview Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveIntegerField(help_text='Order of this turn in the interview.')),
                ('ai_question', models.TextField(help_text='The question asked by the AI.')),
                ('user_answer', models.TextField(blank=True, help_text="The user's transcribed answer.", null=True)),
                ('ai_internal_analysis', models.TextField(blank=True, help_text="AI's internal assessment of the user's answer.", null=True)),
                ('ai_follow_up_feedback', models.TextField(blank=True, help_text="AI's direct feedback or next question.", null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='mock_interview.mockinterviewsession')),
            ],
            options={
                'verbose_name': 'Interview Turn',
                'verbose_name_plural': 'Interview Turns',
                'ordering': ['turn_number'],
                'unique_together': {('session', 'turn_number')},
            },
        ),
    ]
