# Generated by Django 5.1.7 on 2025-08-09 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockinterviewsession',
            name='extracted_resume_text',
            field=models.TextField(blank=True, help_text='Raw extracted text from uploaded resume (for internal use).', null=True),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='parsed_resume_data',
            field=models.JSONField(blank=True, help_text='Structured JSON extracted from resume via AI (job_role, skills, etc.).', null=True),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='resume_file',
            field=models.FileField(blank=True, help_text='Upload your resume in PDF or DOCX format.', null=True, upload_to='mock_interviews/resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='mockinterviewsession',
            name='job_role',
            field=models.CharField(blank=True, help_text='Target job role for the interview.', max_length=255),
        ),
    ]
