# Generated by Django 5.1.7 on 2025-10-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_quiz_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived'), ('PRIVATE', 'Private')], default='PUBLISHED', help_text='Current status of the quiz (e.g., Draft, Pending Approval, Published).', max_length=20),
        ),
    ]
